// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace NoteApplication.Persistence.Entities
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // Note
    public class Note
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title (length: 50)
        public string Description { get; set; } // Description
        public DateTime LastEdited { get; set; } // LastEdited
        public string CreatedBy { get; set; } // CreatedBy (length: 450)
        public bool IsDeleted { get; set; } // IsDeleted
        public int EditCount { get; set; } // EditCount
        public virtual User User { get; set; }

        public Note()
        {
            IsDeleted = false;
            EditCount = 0;
        }
    }

}
// </auto-generated>
